### ISSUE TITLE
newletter is not working

### ISSUE THREAD

**Issue by allinonebenin** [allinonebenin/aiocel#4]
Newsletter is not working as some people mentioned. Please verify first by typing your own real email to see if you get response. Otherwise, we are going to remove this function from the landing page. The script can be found in assets/js/script.js and I also attached a copy of the file here.
[script.js.zip](https://github.com/allinonebenin/aiocel/files/685727/script.js.zip)

**Comment by rfassi** [comment]
Please Joy, work on this issue.

**Comment by allinonebenin** [comment]
Joy, it is all set now. You can move to the contact form.
